name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
      - name: Build
        run: mvn -B install spring-boot:build-image -Dspring-boot.build-image.imageName=ghcr.io/derkoe/snoop
      - name: Push images to ghcr.io
        if: ${{ github.event_name != 'pull_request'}}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          echo "${GITHUB_TOKEN}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker push ghcr.io/derkoe/snoop
